scalar DateTime

type Query {
    # Uses cursor-based pagination
    orders(first: Int, after: String, last: Int, before: String): OrderResponseConnection
    order(id: ID!): OrderResponse!
}

type Mutation {
    create(createOrderRequest: CreateOrderRequest!): OrderResponse!
    cancel(cancelOrderRequest: CancelOrderRequest!): OrderResponse!
}

input CreateOrderRequest {
    userId: ID!
    ticketId: ID!
}

input CancelOrderRequest {
    userId: ID!
    orderId: ID!
}

type OrderResponse {
    id: ID!
    userId: ID!
    ticketId: ID!
    status: String!
    expiresAt: DateTime!
}
