scalar DateTime

type Query {
    # Get a list of user orders with cursor-based pagination
    orders(first: Int, after: String, last: Int, before: String): OrderResponseConnection
    # Get an user order by id
    order(id: ID!): OrderResponse!
}

type Mutation {
    # For user to create an order
    create(createOrderRequest: CreateOrderRequest!): OrderResponse!
    # For user to cancel an order
    cancel(cancelOrderRequest: CancelOrderRequest!): OrderResponse!
}

# Input values to create an order
input CreateOrderRequest {
    userId: ID!
    ticketId: ID!
}

# Input values to cancel an order
input CancelOrderRequest {
    userId: ID!
    orderId: ID!
}

type OrderResponse {
    id: ID!
    userId: ID!
    ticketId: ID!
    status: String!
    expiresAt: DateTime!
}
