apiVersion: v1
kind: Secret
metadata:
  name: event-ticketing-secret
  namespace: default
type: Opaque
stringData:
  # TODO: Remove this for prod
  db-username: mypostgresuser
  db-password: mypostgressecret
