spring.application.name=tickets
spring.main.banner-mode=off
server.port=8082
# The optional: prefix ensures the app still boots up in production if the local .env is missing
spring.config.import=optional:file:./infra/.env[.properties]

# GraphQL
spring.graphql.graphiql.enabled=true

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:54321/tickets
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Kafka producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.objectmapper=jacksonObjectMapper
spring.kafka.producer.properties.max.block.ms=15000

# Security
# Replace with your Keycloak host, realm name, and port
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/my-graphql-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/my-graphql-realm/protocol/openid-connect/certs
# The custom client ID or intended audience assigned in Keycloak
spring.security.oauth2.resourceserver.jwt.audience=http://my-graphql-api

# Logging
logging.level.com.eventtickets.tickets=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
